### ISSUE TITLE
Get event even if the application doesn't have the focus

### ISSUE THREAD

**Issue by chifteur** [DevDecoder/HIDDevices#3]
Hello,

Thank you for your library, 
I'm triing to use it to handle game pad for a PTZ Camera controls application.

I develop it based on your Dependency Sample app.
I noticed that I received event only if my application has the focus.
Is it normal ?

Thank you for your help.

**Comment by chifteur** [comment]
After I read again the readme I'm within XBox case.

`Microsoft XBox One for Windows Controller (Note that it appears XInput-compatible HID device driver only transmits events from the HID device whilst the current process has a focussed window, so console applications/background services don't appear to work! This is not a bug in this library.)`

**Comment by thargy** [comment]
I feel you @chifteur. that took me days to track down, I've yet to find a document for the 'feature' but it's definitely only happening with XBox controllers so far.
