### ISSUE TITLE
In a custom controller, buttons higher than Button 15 (Button 16, id 17) don't send changes.

### ISSUE THREAD

**Issue by dennisrijsdijk** [DevDecoder/HIDDevices#5]
I'm currently mapping out my Logitech G29 steering wheel with HIDDevices, and due to having more buttons, they don't fit in button0-button15. They show up properly when using `devices.ControlChanges().Subscribe`, but not G29.Changes.Subscribe. I get events for Button 0 through Button 15 and my axes, but not the rest of the buttons. When I press one of the buttons that doesn't work after starting the program, it does detect the keypress, as it lists the initial controls in my console.; However, it only lists my axes, HAT and Button 0 through Button 15.

```cs
    [Control(ButtonPage.Button15)] // ID 16
    [Required]
    public bool FourthGear => GetValue<bool>();
    
    [Control(17)] // Button 16
    [Required]
    public bool FifthGear => GetValue<bool>();
```

When I tested changing FourthGear to ID 16 instead of Button15, it stopped working. It looks like it's not possible to specify a Usage either, because attributes need to be compile-time constants, and I don't believe I can get the Usage as a compiletime constant. I've tried Usage.Get(16), which doesn't work as it's not a compiletime constant.

**Comment by thargy** [comment]
Button 16 would be `0x90011` (or `589841` in decimal), as a full Control ID encodes both the Usage Page (`0x9` - Button Usage Page) and the short usage ID (`0x11` or `17` - Button 16). The `ControlAttribute` needs the full ID to know exactly which control you mean.

See the definition of `Button15` which is defined as `0x00090010`:
```csharp
        /// <summary>
        ///     Button 15 Usage.
        /// </summary>
        [Description("Button 15")]
        Button15 = 0x00090010
```

So `[Control(0x90011)]` or `[Control(589841)]` should work.

**Comment by dennisrijsdijk** [comment]
I'll give that a shot, thanks!

**Comment by dennisrijsdijk** [comment]
That didn't seem to work, I tried both 0x90011 and 589841 but it still doesn't register.

**Comment by dennisrijsdijk** [comment]
I wrote some code to print out the FullId in hex and decimal and it does match what you sent. I think it may be related to the OfType<Enum>() call in the constructor of ControlAttribute.

**Comment by thargy** [comment]
> I think it may be related to the OfType() call in the constructor of ControlAttribute.

Good spot. I did test with my Saitek X52 which also has more than 16 buttons, but I didn't create a device class for it. To be honest, I added that functionality as an afterthought as I mostly use the lower-level APIs, so my bad!

I added the OfType() to support passing in enums directly without needing to cast them to `uint`, and to validate that the control was a known one. However, I didn't add support for user-defined usages which I added later. It occurs in a few places so I'll find and fix them now.

For anyone interested, the enums only define the first 16 values of any range to keep them manageable. Buttons are specified as a range from 0-65534, so it's impractical to list everyone. You can however create them on demand (using `Usage.Get`) and they will still be correctly named, etc.  However, that means every possible enum is not available at compile time so you should be able to use the raw id equivalent wherever the enum is accepted.

**Comment by dennisrijsdijk** [comment]
Tested and verified as resolved, thanks!
