### ISSUE TITLE
Current Code (Aug 17) has about 80 Errors

### ISSUE THREAD

**Issue by sojatay** [DevDecoder/HIDDevices#8]
All Namespace declarations are terminated with a ; instead of  {}

**Comment by thargy** [comment]
You need to be using C#10 when building yourself.

[See File-scoped namespaces](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces)

**Comment by sojatay** [comment]
Thank you. Was not aware of that C#10 change
