### ISSUE TITLE
How can i calibrate my HID device

### ISSUE THREAD

**Issue by EAS-Innovations** [DevDecoder/HIDDevices#9]
My Gamepad has two analog sticks. The problem is all four axes work from middle position to one direction. Mittle position has value -1. In one direction it makes the complete rage from -1 over 0 to 1. But the other direction doesn't make anything. So the Question is how to define the range or calibrate it. 
In Joystick settings in Windows Control panel I can move the hole range and it is calibrated.
Thank you for this great lib

**Comment by thargy** [comment]
Are you using the 'Gamepad' controller?  These are convenience classes that convert the raw inputs from whatever device you have to convenient ranges/values.  It is possible your device is returning values that are not expected and so not mapping correctly.

You can always subscribe directly to the device changes and see what the actual values are that are coming through - the [Dependency Injection Sample](https://github.com/DevDecoder/HIDDevices/blob/master/HIDDevices.Sample/Samples/DependencyInjectionSample.cs) shows how, and you can use that sample to see the raw values.

Alternatively, you can extend the controller class you are experiencing problems with and override the `OnControlChange` method to get the `IList<ControlChange> changes`, which you can examine to see what values you are actually getting from the device.

Once you determine the actual values returned by your device you can create your own controller with your own custom type converters.  The [Gamepad class](https://github.com/DevDecoder/HIDDevices/blob/master/HIDDevices/Controllers/Gamepad.cs) is a good example, and you can see how to write convertors by looking at the code in the [Converters folder](https://github.com/DevDecoder/HIDDevices/tree/master/HIDDevices/Converters).

The library is designed to be as extensible as possible, so you can directly connect to devices and see the raw data, or create custom controllers to map values any way you want.  The readme is reasonably detailed, and I've commented the code extensively.

Thanks for using the library!

**Comment by EAS-Innovations** [comment]
Thank you for your support. The problem is in HidSharp. I will search there for the problem.

**Comment by thargy** [comment]
> Thank you for your support. The problem is in HidSharp. I will search there for the problem.

You can find it at https://www.zer7.com/software/hidsharp, and Zer has a forum at https://forum.zer7.com/ that he seems to check occasionally.  I'd be grateful if you let me know what the bug is when you find it as I have considered replacing the dependency on HidSharp eventually as it's not had any updates in over 3 years, and it's pretty long in the tooth.  I wanted to get the front-end API looking right first, (i.e. using Rx and being fully asynchronous); and I wanted to expose the Hid Usage Tables, which are the two primary features that this package exposes and hopefully they make consuming USB devices much easier in modern C#.

**Comment by EAS-Innovations** [comment]
I decided to implement HID by my self in using `[DllImport("hid.dll")]` I wasn't able to debug the HidSharp in a way to see the raw values. All four modes `//#define SINGLE_THREADED_POLLING_APPROACH
//#define SINGLE_THREADED_WAITHANDLE_APPROACH
//#define THREAD_POOL_RECEIVED_EVENT_APPROACH
#define RAW_APPROACH` didn't read values and because I had to get it run today I selected the quick way. 
For your information the Joystick is an Arduino Device
